### ISSUE TITLE
Still being developed?

### ISSUE THREAD

**Issue by chWolfgang** [VeXHarbinger/DrawPool#7]
Hi,
Wondering if this still being developed? Love the idea, but adding more cards to it would be great. 
Thanks for your time!

**Comment by VeXHarbinger** [comment]
TBH I haven't had a second to download the latest update yet, but I do plan on it.
I wrote it to be modular and started to add in the recruit mechanic, so it should be easy to extend.

Did you see if something specific wasn't working or is there a new mechanic you wanted to see added in?

**Comment by chWolfgang** [comment]
I am glad to hear you may be able to add features to this. The couple that come to mind are the Pally cards that pull minions of a certain cost. "Call to Adventure" and "Crystology" come to mind. Also, the Hunter card "Ursatron" to dray Mechs. Or, "Arcane Fletcher".
For the mage spell "Book of Specters" could give a count of "spells" v other cards so you know your chances?
Rogue "Raiding Party" would be nice.
Shaman "Storm Chaser"
Warlock "Sense Demons"
etc..
The DRAW mechanic seems very popular these days. That is why I keep looking at this add-on.
I hope this isn't too overwhelming. But it seems like this could be a VERY useful add-on. And there is WILD as well.. ;)
Thank you for time on all this.

**Comment by VeXHarbinger** [comment]
New development has been posted
